name: "dhondu maharaj"

on: workflow_dispatch
      
jobs:
  terraform-job:
    name: terraform job
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      # - name: Terraform installer
      #   uses: autero1/action-terraform@v3.0.1
      #   with: 
      #     version: 1.13.0
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: f79bff9b-6bbb-4e7a-948c-6ddb3e615071
          tenant-id: 4cf44098-fae1-43c3-95f4-893895b698a0
          subscription-id: 075d036c-4cbd-46d6-a39c-519dc57956b3
         
         
