name: "dhondu maharaj"

on: workflow_dispatch
      
jobs:
  terraform-job:
    name: terraform job
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Terraform installer
        uses: autero1/action-terraform@v3.0.1
        with: 
          version: 1.13.0
