name: "dhondu maharaj"

on: workflow_dispatch

permissions:
  id-token: write
  contents: read      
  
jobs:
  terraform-job:
    name: terraform job
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      # - name: Terraform installer
      #   uses: autero1/action-terraform@v3.0.1
      #   with: 
      #     version: 1.13.0



      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Azure Login
      #   uses: Azure/login@v2.3.0
      #   with:
      #     client-id: f79bff9b-6bbb-4e7a-948c-6ddb3e615071
      #     tenant-id: 4cf44098-fae1-43c3-95f4-893895b698a0
      #     subscription-id: 075d036c-4cbd-46d6-a39c-519dc57956b3

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: environment/dev

      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: environment/dev
      
      # - name: Terraform Validate
      #   id: validate
      #   run: terraform validate -no-color
      #   working-directory: environment/dev
      
      # - name: Terraform Plan
      #   id: plan
      #   run: terraform plan -no-color -input=false
      #   continue-on-error: true  
      #   working-directory: environment/dev
                  
         
         
