name: "dhondu maharaj"

on:
  push:
    branches:
      - 'main'
      - 'features/**'
      - 'hotfix/**'
      
jobs:
  terraforminit:
    name: dhondu maharaj
    runs-on: dhondu-maharaj
    steps:
     - name: dhondu maharaj rocks
      run: echo dhondu maharaj
