name: "dhondu maharaj"

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
      - 'hotfix/**'
      
jobs:
  dhondumaharaj:
    name: dhondu maharaj
    runs-on: dhondu-maharaj
    steps:
     # - name: dhondu maharaj rocks
     #   run: echo dhondu maharaj

     - name: terraforminit
       run: terraform init
